// Scanner module — discover Axum routes as apcore modules.
//
// Provides a native scanner that reads the compile-time route metadata
// registry (`ap_handler!` / `register_route`) and an optional OpenAPI scanner
// (feature `openapi`) for apps that publish an OpenAPI 3.x document, e.g. one
// generated by utoipa.

pub mod native;

#[cfg(feature = "openapi")]
pub mod openapi;

use std::path::Path;

use apcore_toolkit::ScannedModule;
use async_trait::async_trait;

use crate::errors::AxumApcoreError;

/// Trait for Axum route scanners.
///
/// axum-apcore's own scanner trait, not a wrapper around an apcore-toolkit
/// trait: it carries the include/exclude filters on every `scan` call.
/// Nothing in the apcore ecosystem dispatches over
/// `apcore_toolkit::BaseScanner`, so implementing that trait would buy no
/// interoperability today. Migrating onto it is possible (the next
/// apcore-toolkit-rust release makes `BaseScanner::scan` fallible) but is
/// out of scope for now.
///
/// Axum's `Router` is type-erased, so no scanner can introspect it: the
/// native scanner reads the route metadata registry, and the OpenAPI scanner
/// reads the document bound at its construction. Both ignore the `app`
/// argument.
#[async_trait]
pub trait AxumScanner: Send + Sync {
    /// Scan routes and return module definitions.
    async fn scan(
        &self,
        app: &axum::Router,
        include: Option<&str>,
        exclude: Option<&str>,
    ) -> Result<Vec<ScannedModule>, AxumApcoreError>;

    /// Human-readable scanner name.
    fn source_name(&self) -> &str;
}

/// Factory function to get a scanner by source name.
///
/// Equivalent to `get_scanner_with_spec(source, None)`. The `"openapi"`
/// source needs a document, which a source name alone cannot supply, so it
/// is rejected here; use [`get_scanner_with_spec`] for it.
pub fn get_scanner(source: &str) -> Result<Box<dyn AxumScanner>, AxumApcoreError> {
    get_scanner_with_spec(source, None)
}

/// Factory function to get a scanner by source name, binding an OpenAPI
/// document for the `"openapi"` source.
///
/// - `"native"` — the route metadata registry scanner; `openapi_spec` is
///   ignored.
/// - `"openapi"` (feature `openapi`) — an `OpenAPIScanner` bound to
///   `openapi_spec`, which is required.
///
/// # Errors
///
/// [`AxumApcoreError::Scanner`] for an unknown source (including `"openapi"`
/// when the `openapi` feature is disabled) or for `"openapi"` without a
/// document.
#[cfg_attr(not(feature = "openapi"), allow(unused_variables))]
pub fn get_scanner_with_spec(
    source: &str,
    openapi_spec: Option<serde_json::Value>,
) -> Result<Box<dyn AxumScanner>, AxumApcoreError> {
    match source {
        "native" => Ok(Box::new(native::NativeAxumScanner::new())),
        #[cfg(feature = "openapi")]
        "openapi" => match openapi_spec {
            Some(spec) => Ok(Box::new(openapi::OpenAPIScanner::with_spec(spec))),
            None => Err(AxumApcoreError::Scanner(
                openapi::MISSING_SPEC_MESSAGE.to_string(),
            )),
        },
        other => Err(AxumApcoreError::Scanner(format!(
            "Unknown scanner source: '{}'. Available: native{}",
            other,
            if cfg!(feature = "openapi") {
                ", openapi"
            } else {
                " ('openapi' requires the `openapi` feature)"
            }
        ))),
    }
}

/// Build the scanner for `source`, loading the OpenAPI document from
/// `openapi_spec_path` when (and only when) the source is `"openapi"`.
///
/// Shared by `AxumApcore::scan` (settings) and the `scan` CLI command.
#[cfg(feature = "openapi")]
pub(crate) fn get_scanner_with_spec_path(
    source: &str,
    openapi_spec_path: Option<&Path>,
) -> Result<Box<dyn AxumScanner>, AxumApcoreError> {
    let spec = match (source, openapi_spec_path) {
        ("openapi", Some(path)) => Some(openapi::load_spec_file(path)?),
        _ => None,
    };
    get_scanner_with_spec(source, spec)
}

/// Without the `openapi` feature there is no document to load: every
/// source resolves through [`get_scanner`].
#[cfg(not(feature = "openapi"))]
pub(crate) fn get_scanner_with_spec_path(
    source: &str,
    _openapi_spec_path: Option<&Path>,
) -> Result<Box<dyn AxumScanner>, AxumApcoreError> {
    get_scanner(source)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_get_scanner_native() {
        let scanner = get_scanner("native").unwrap();
        assert_eq!(scanner.source_name(), "native");
    }

    #[test]
    fn test_get_scanner_unknown() {
        let result = get_scanner("unknown");
        assert!(result.is_err());
    }

    #[test]
    fn test_get_scanner_with_spec_native_ignores_spec() {
        let scanner = get_scanner_with_spec("native", Some(serde_json::json!({}))).unwrap();
        assert_eq!(scanner.source_name(), "native");
    }

    #[cfg(feature = "openapi")]
    #[test]
    fn test_get_scanner_openapi_without_spec_is_rejected() {
        match get_scanner("openapi") {
            Err(AxumApcoreError::Scanner(msg)) => assert!(msg.contains("APCORE_OPENAPI_SPEC")),
            Err(other) => panic!("expected a Scanner error, got {other:?}"),
            Ok(_) => panic!("expected get_scanner(\"openapi\") to be rejected"),
        }
    }

    #[cfg(feature = "openapi")]
    #[tokio::test]
    async fn test_get_scanner_with_spec_openapi_scans_bound_document() {
        let spec = serde_json::json!({
            "openapi": "3.0.3",
            "info": {"title": "T", "version": "1.0.0"},
            "paths": {"/items": {"get": {"operationId": "list_items_get", "tags": ["items"],
                                         "responses": {"200": {"description": "OK"}}}}}
        });
        let scanner = get_scanner_with_spec("openapi", Some(spec)).unwrap();
        assert_eq!(scanner.source_name(), "openapi");
        let modules = scanner
            .scan(&axum::Router::new(), None, None)
            .await
            .unwrap();
        assert_eq!(modules.len(), 1);
        assert_eq!(modules[0].module_id, "items.list_items.get");
        assert_eq!(modules[0].target, "axum::list_items_get");
    }

    #[cfg(feature = "openapi")]
    #[test]
    fn test_get_scanner_with_spec_path_loads_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("spec.yaml");
        std::fs::write(&path, "openapi: 3.1.0\npaths: {}\n").unwrap();
        let scanner = get_scanner_with_spec_path("openapi", Some(&path)).unwrap();
        assert_eq!(scanner.source_name(), "openapi");
        assert!(get_scanner_with_spec_path("openapi", None).is_err());
        // The path is only read for the openapi source.
        let native =
            get_scanner_with_spec_path("native", Some(Path::new("/nonexistent/spec.json")))
                .unwrap();
        assert_eq!(native.source_name(), "native");
    }

    #[cfg(not(feature = "openapi"))]
    #[test]
    fn test_get_scanner_openapi_unknown_without_feature() {
        let spec = serde_json::json!({"openapi": "3.1.0", "paths": {}});
        match get_scanner_with_spec("openapi", Some(spec)) {
            Err(AxumApcoreError::Scanner(msg)) => assert!(msg.contains("`openapi` feature")),
            Err(other) => panic!("expected a Scanner error, got {other:?}"),
            Ok(_) => panic!("expected 'openapi' to be unknown without the feature"),
        }
    }
}
