// OpenAPI-based scanner for Axum apps.
//
// Turns an OpenAPI 3.0/3.1 document into apcore modules. The document is
// typically generated by utoipa (`serde_json::to_value(ApiDoc::openapi())`),
// but any OpenAPI 3.x JSON/YAML document works.
//
// Document traversal, schema extraction, `deprecated` handling, warnings and
// ID deduplication are delegated to `apcore_toolkit::OpenAPIScanner`. This
// module only layers axum-apcore's user-visible naming on top, through the
// toolkit's hooks:
//
// - `module_id`: `{tag}.{func}.{method}` when the operation has an
//   operationId; otherwise the toolkit's path-derived ID (`health.get`).
// - `target`: `axum::{operationId}` when the operation has an operationId;
//   otherwise the toolkit's `"GET /path"` route descriptor. `target` is the
//   key `AxumApcore::register_handler` binds a handler to.
// - `suggested_alias`: `generate_suggested_alias(path, method)`.
//
// Axum's `Router` is type-erased and carries no OpenAPI document, so the
// document is bound to the scanner at construction (`with_spec`) rather than
// recovered from the `Router` passed to `AxumScanner::scan`.

use std::future::Future;
use std::path::Path;

use apcore_toolkit::openapi_scanner::{
    OpenAPIScanner as ToolkitOpenAPIScanner, ScanOptions, ScannerError,
};
use apcore_toolkit::{generate_suggested_alias, ScannedModule};
use async_trait::async_trait;
use futures::FutureExt;
use serde_json::Value;

use crate::errors::AxumApcoreError;
use crate::scanner::AxumScanner;

/// Error message for an `openapi` scan that has no document to scan.
pub(crate) const MISSING_SPEC_MESSAGE: &str =
    "the 'openapi' scanner source needs an OpenAPI 3.x document, and an axum Router \
     does not carry one. Bind it with OpenAPIScanner::with_spec(spec) or \
     get_scanner_with_spec(\"openapi\", Some(spec)), set APCORE_OPENAPI_SPEC to a \
     JSON/YAML file (ApcoreSettings::openapi_spec), pass --spec to the `scan` CLI \
     command, or set CreateCliConfig::openapi_spec";

/// Scanner that turns an OpenAPI 3.0/3.1 document into apcore modules.
///
/// Requires the `openapi` feature. Two ways to use it:
///
/// - **Bound document** — [`OpenAPIScanner::with_spec`] binds the document at
///   construction, so the scanner works through the [`AxumScanner`] trait
///   (`get_scanner_with_spec("openapi", ..)`, `AxumApcore::init_app`, the CLI).
/// - **Direct call** — [`OpenAPIScanner::scan_spec`] scans any document
///   passed in, whether or not one is bound.
///
/// ```ignore
/// use axum_apcore::{AxumScanner, OpenAPIScanner};
///
/// let spec = serde_json::to_value(ApiDoc::openapi())?; // utoipa
/// let scanner = OpenAPIScanner::with_spec(spec);
/// let modules = scanner.scan(&router, None, None).await?;
/// ```
#[derive(Debug, Clone)]
pub struct OpenAPIScanner {
    /// Strip a trailing `_{method}` from the operationId when building the
    /// `func` segment of `{tag}.{func}.{method}` (default `true`):
    /// `get_user_get` + `GET` -> `users.get_user.get`. When `false`, the raw
    /// operationId is used: `users.get_user_get.get`.
    ///
    /// Despite its name, this is **not** the deprecated `simplify_ids`
    /// display simplification of apcore PROTOCOL_SPEC §5.13.11 (which
    /// rewrites `module_id` to a shortened function name). With the default
    /// `true`, it produces exactly the canonical ID fastapi-apcore derives
    /// with *its* default `simplify_ids=False` (`_strip_method_suffix`: strip
    /// only the trailing `_{method}`); axum-apcore has no counterpart of
    /// fastapi-apcore's deprecated `simplify_ids=True` mode. It therefore
    /// emits no deprecation warning. It only affects operations that have an
    /// operationId.
    pub simplify_ids: bool,
    /// The document scanned by [`AxumScanner::scan`], if bound.
    spec: Option<Value>,
}

impl OpenAPIScanner {
    /// Create a scanner with no bound document and `simplify_ids = true`.
    ///
    /// Use [`OpenAPIScanner::scan_spec`] with it, or bind a document with
    /// [`OpenAPIScanner::with_spec`] to scan through [`AxumScanner`].
    pub fn new() -> Self {
        Self {
            simplify_ids: true,
            spec: None,
        }
    }

    /// Create a scanner with an explicit `simplify_ids` setting (see the
    /// field docs: it strips the trailing `_{method}` from operationIds and
    /// is not the deprecated §5.13.11 display simplification).
    pub fn with_simplify_ids(simplify_ids: bool) -> Self {
        Self {
            simplify_ids,
            spec: None,
        }
    }

    /// Create a scanner bound to `spec`, an OpenAPI 3.0/3.1 document, with
    /// `simplify_ids = true` (set the public field to change it).
    ///
    /// [`AxumScanner::scan`] scans this document and ignores its `Router`
    /// argument.
    pub fn with_spec(spec: Value) -> Self {
        Self {
            simplify_ids: true,
            spec: Some(spec),
        }
    }

    /// The document bound by [`OpenAPIScanner::with_spec`], if any.
    pub fn spec(&self) -> Option<&Value> {
        self.spec.as_ref()
    }

    /// Scan an OpenAPI 3.0/3.1 document and produce scanned modules.
    ///
    /// Synchronous; independent of any document bound with
    /// [`OpenAPIScanner::with_spec`].
    ///
    /// # Errors
    ///
    /// - [`AxumApcoreError::Scanner`] when `spec` is not OpenAPI 3.0.x/3.1.x
    ///   (missing `openapi` key, or a Swagger 2.0 document).
    /// - [`AxumApcoreError::Regex`] when `include` / `exclude` is not a valid
    ///   regex.
    pub fn scan_spec(
        &self,
        spec: &Value,
        include: Option<&str>,
        exclude: Option<&str>,
    ) -> Result<Vec<ScannedModule>, AxumApcoreError> {
        resolve_ready(self.scan_document(spec, include, exclude))?
    }

    /// Delegate to `apcore_toolkit::OpenAPIScanner`, with axum's naming hooks.
    async fn scan_document(
        &self,
        spec: &Value,
        include: Option<&str>,
        exclude: Option<&str>,
    ) -> Result<Vec<ScannedModule>, AxumApcoreError> {
        let options = self.scan_options(include, exclude);
        ToolkitOpenAPIScanner::new()
            .scan(spec, &options)
            .await
            .map_err(scanner_error_to_axum)
    }

    /// Build the toolkit `ScanOptions`: filters plus axum's naming hooks.
    fn scan_options(&self, include: Option<&str>, exclude: Option<&str>) -> ScanOptions {
        let simplify_ids = self.simplify_ids;
        // Field assignment rather than a struct literal, so a field added to
        // `ScanOptions` by a later toolkit release does not break this build.
        let mut options = ScanOptions::new();
        options.include = include.map(str::to_string);
        options.exclude = exclude.map(str::to_string);
        options.derive_module_id = Some(Box::new(move |_path, method, operation| {
            axum_module_id(method, operation, simplify_ids)
        }));
        options.transform_module = Some(Box::new(restore_axum_naming));
        options
    }
}

impl Default for OpenAPIScanner {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl AxumScanner for OpenAPIScanner {
    /// Scan the document bound with [`OpenAPIScanner::with_spec`]. The
    /// `Router` argument is ignored: it carries no OpenAPI document.
    async fn scan(
        &self,
        _app: &axum::Router,
        include: Option<&str>,
        exclude: Option<&str>,
    ) -> Result<Vec<ScannedModule>, AxumApcoreError> {
        let spec = self
            .spec
            .as_ref()
            .ok_or_else(|| AxumApcoreError::Scanner(MISSING_SPEC_MESSAGE.to_string()))?;
        self.scan_document(spec, include, exclude).await
    }

    fn source_name(&self) -> &str {
        "openapi"
    }
}

/// Load an OpenAPI document from a local JSON or YAML file.
///
/// The format is sniffed from the content, not the extension: a document
/// whose first non-whitespace character is `{` is parsed as JSON, anything
/// else as YAML. Only local paths are accepted (no URL fetching).
///
/// # Errors
///
/// [`AxumApcoreError::Config`] naming the path when the file cannot be read
/// or does not parse.
pub fn load_spec_file(path: &Path) -> Result<Value, AxumApcoreError> {
    let text = std::fs::read_to_string(path).map_err(|e| {
        AxumApcoreError::Config(format!(
            "cannot read OpenAPI spec '{}': {e}",
            path.display()
        ))
    })?;
    parse_spec_text(&text).map_err(|e| {
        AxumApcoreError::Config(format!("malformed OpenAPI spec '{}': {e}", path.display()))
    })
}

/// Parse a JSON or YAML OpenAPI document (see [`load_spec_file`]).
fn parse_spec_text(text: &str) -> Result<Value, String> {
    if text.trim_start().starts_with('{') {
        serde_json::from_str(text).map_err(|e| format!("invalid JSON: {e}"))
    } else {
        serde_yaml::from_str(text).map_err(|e| format!("invalid YAML: {e}"))
    }
}

/// Drive a future that is expected to complete without suspending.
///
/// `apcore_toolkit::OpenAPIScanner::scan` is an `async fn` that performs no
/// I/O and contains no `.await` (toolkit 0.12), so its future is ready on the
/// first poll. `now_or_never` polls it exactly once with a no-op waker and
/// never parks the thread, so — unlike `futures::executor::block_on` — this
/// cannot deadlock, not even when `scan_spec` is called from inside a
/// single-threaded Tokio runtime. Should a later toolkit release add a real
/// suspension point, this returns an error instead of hanging.
fn resolve_ready<F: Future>(future: F) -> Result<F::Output, AxumApcoreError> {
    future.now_or_never().ok_or_else(|| {
        AxumApcoreError::Scanner(
            "apcore-toolkit's OpenAPI scan suspended, so it cannot be driven \
             synchronously; use the async AxumScanner::scan (OpenAPIScanner::with_spec) \
             instead of scan_spec"
                .to_string(),
        )
    })
}

/// Map the toolkit's scan error onto axum-apcore's error type.
///
/// An invalid filter regex keeps the `Regex` variant it had before the scan
/// was delegated; every other case (today: a non-OpenAPI-3.x document) is a
/// `Scanner` error. The catch-all binding keeps this compiling if the toolkit
/// adds variants.
fn scanner_error_to_axum(error: ScannerError) -> AxumApcoreError {
    match error {
        ScannerError::Pattern(e) => AxumApcoreError::Regex(e),
        other => AxumApcoreError::Scanner(other.to_string()),
    }
}

/// The operation's operationId, if present and non-empty.
fn operation_id_of(operation: &Value) -> Option<&str> {
    operation
        .get("operationId")
        .and_then(Value::as_str)
        .filter(|id| !id.is_empty())
}

/// `derive_module_id` hook: axum's `{tag}.{func}.{method}` for operations
/// with an operationId; `None` (the toolkit's path derivation) otherwise.
///
/// `tag` is the first string tag or `"default"`; `func` is the operationId,
/// with its trailing `_{method}` stripped when `simplify_ids` is set.
fn axum_module_id(method: &str, operation: &Value, simplify_ids: bool) -> Option<String> {
    let operation_id = operation_id_of(operation)?;
    let tag = operation
        .get("tags")
        .and_then(Value::as_array)
        .and_then(|tags| tags.iter().find_map(Value::as_str))
        .unwrap_or("default");
    let func = if simplify_ids {
        strip_method_suffix(operation_id, method)
    } else {
        operation_id.to_string()
    };
    Some(format!("{tag}.{func}.{}", method.to_lowercase()))
}

/// `transform_module` hook: restore axum's `target` and `suggested_alias`.
///
/// Reads the toolkit's documented metadata (`openapi.operation_id`,
/// `url_path`, `http_method`). Without an operationId the toolkit's
/// `"GET /path"` target is kept: it is unique per operation, so it is a
/// usable `register_handler` key.
fn restore_axum_naming(mut module: ScannedModule) -> Option<ScannedModule> {
    let operation_id = module
        .metadata
        .get("openapi")
        .and_then(|openapi| openapi.get("operation_id"))
        .and_then(Value::as_str)
        .map(str::to_string);
    if let Some(operation_id) = operation_id {
        module.target = format!("axum::{operation_id}");
    }

    let path = module.metadata.get("url_path").and_then(Value::as_str);
    let method = module.metadata.get("http_method").and_then(Value::as_str);
    if let (Some(path), Some(method)) = (path, method) {
        module.suggested_alias = Some(generate_suggested_alias(path, method));
    }
    Some(module)
}

/// Strip a method suffix from an operationId.
///
/// E.g., "get_user_get" with method "get" -> "get_user". Same algorithm as
/// fastapi-apcore's `OpenAPIScanner._strip_method_suffix`.
fn strip_method_suffix(operation_id: &str, method: &str) -> String {
    let suffix = format!("_{}", method.to_lowercase());
    match operation_id.strip_suffix(&suffix) {
        Some(stripped) => stripped.to_string(),
        None => operation_id.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn sample_spec() -> Value {
        json!({
            "openapi": "3.1.0",
            "info": {"title": "Test API", "version": "1.0.0"},
            "paths": {
                "/api/users/{id}": {
                    "get": {
                        "operationId": "get_user_get",
                        "summary": "Get a user by ID",
                        "tags": ["users"],
                        "parameters": [{
                            "name": "id",
                            "in": "path",
                            "required": true,
                            "schema": {"type": "string"}
                        }],
                        "responses": {
                            "200": {
                                "description": "Success",
                                "content": {
                                    "application/json": {
                                        "schema": {
                                            "type": "object",
                                            "properties": {
                                                "name": {"type": "string"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "/api/tasks": {
                    "post": {
                        "operationId": "create_task_post",
                        "summary": "Create a task",
                        "tags": ["tasks"],
                        "requestBody": {
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "type": "object",
                                        "properties": {
                                            "title": {"type": "string"}
                                        },
                                        "required": ["title"]
                                    }
                                }
                            }
                        },
                        "responses": {
                            "201": {
                                "description": "Created",
                                "content": {
                                    "application/json": {
                                        "schema": {
                                            "type": "object",
                                            "properties": {
                                                "id": {"type": "string"},
                                                "title": {"type": "string"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        })
    }

    /// A utoipa-style document exercising tag fallback, a path-level
    /// `parameters` key, an operationId without a method suffix, and a
    /// camelCase operationId.
    fn naming_spec() -> Value {
        json!({
            "openapi": "3.1.0",
            "info": {"title": "T", "version": "2.5.0"},
            "paths": {
                "/api/users/{id}": {
                    "parameters": [{"name": "id", "in": "path", "required": true,
                                    "schema": {"type": "string"}}],
                    "get": {"operationId": "get_user_get", "summary": "Get a user",
                            "tags": ["users"], "responses": {"200": {"description": "OK"}}},
                    "delete": {"operationId": "delete_user_delete", "summary": "Delete a user",
                               "responses": {"204": {"description": "gone"}}}
                },
                "/api/users": {
                    "post": {"operationId": "create_user", "summary": "Create",
                             "tags": ["users"], "responses": {"201": {"description": "C"}}}
                },
                "/items/{item_id}/sub": {
                    "put": {"operationId": "replaceItemSub", "tags": ["Items", "extra"],
                            "description": "Line one\nLine two",
                            "responses": {"200": {"description": "OK"}}}
                }
            }
        })
    }

    /// Sorted `(module_id, target, suggested_alias)` triples.
    fn naming_of(modules: &[ScannedModule]) -> Vec<(String, String, String)> {
        let mut triples: Vec<(String, String, String)> = modules
            .iter()
            .map(|m| {
                (
                    m.module_id.clone(),
                    m.target.clone(),
                    m.suggested_alias.clone().unwrap_or_default(),
                )
            })
            .collect();
        triples.sort();
        triples
    }

    fn triple(id: &str, target: &str, alias: &str) -> (String, String, String) {
        (id.to_string(), target.to_string(), alias.to_string())
    }

    #[test]
    fn test_scan_spec() {
        let scanner = OpenAPIScanner::new();
        let spec = sample_spec();
        let modules = scanner.scan_spec(&spec, None, None).unwrap();

        assert_eq!(modules.len(), 2);

        let get_mod = modules
            .iter()
            .find(|m| m.module_id.contains("get_user"))
            .unwrap();
        assert_eq!(get_mod.module_id, "users.get_user.get");
        assert_eq!(get_mod.target, "axum::get_user_get");
        assert_eq!(get_mod.description, "Get a user by ID");
        assert!(get_mod.annotations.as_ref().unwrap().readonly);

        let post_mod = modules
            .iter()
            .find(|m| m.module_id.contains("create_task"))
            .unwrap();
        assert_eq!(post_mod.module_id, "tasks.create_task.post");
        assert_eq!(post_mod.target, "axum::create_task_post");
    }

    /// Target of the one `naming_spec` operation whose axum-derived ID is not
    /// a legal apcore ID (uppercase tag and operationId).
    const UPPERCASE_ID_TARGET: &str = "axum::replaceItemSub";

    /// Splits off the `UPPERCASE_ID_TARGET` module and checks it. Its ID is
    /// the only one allowed to differ by toolkit release: apcore-toolkit 0.12
    /// passes the hook's `Items.replaceItemSub.put` through, while later
    /// releases normalise every emitted ID into apcore's alphabet
    /// (`items.replace_item_sub.put`). The old spelling never registered, so
    /// no working ID changes; accept both until the toolkit floor is raised.
    fn without_uppercase_id_module(
        triples: Vec<(String, String, String)>,
    ) -> Vec<(String, String, String)> {
        let (uppercase, rest): (Vec<_>, Vec<_>) = triples
            .into_iter()
            .partition(|t| t.1 == UPPERCASE_ID_TARGET);
        assert_eq!(
            uppercase.len(),
            1,
            "expected one {UPPERCASE_ID_TARGET} module"
        );
        let (id, _, alias) = &uppercase[0];
        assert!(
            id == "Items.replaceItemSub.put" || id == "items.replace_item_sub.put",
            "unexpected module_id {id:?}"
        );
        assert_eq!(alias, "items.sub.update");
        rest
    }

    /// Pins the naming produced before the scan was delegated to the
    /// toolkit (captured from axum-apcore 0.3.0 on the same document) for
    /// every ID apcore can register; see [`without_uppercase_id_module`] for
    /// the one that it cannot.
    #[test]
    fn test_scan_spec_naming_unchanged_for_operation_ids() {
        let spec = naming_spec();

        let simplified = OpenAPIScanner::new().scan_spec(&spec, None, None).unwrap();
        assert_eq!(
            without_uppercase_id_module(naming_of(&simplified)),
            vec![
                triple(
                    "default.delete_user.delete",
                    "axum::delete_user_delete",
                    "api.users.delete"
                ),
                triple(
                    "users.create_user.post",
                    "axum::create_user",
                    "api.users.create"
                ),
                triple("users.get_user.get", "axum::get_user_get", "api.users.get"),
            ]
        );

        let raw = OpenAPIScanner::with_simplify_ids(false)
            .scan_spec(&spec, None, None)
            .unwrap();
        assert_eq!(
            without_uppercase_id_module(naming_of(&raw)),
            vec![
                triple(
                    "default.delete_user_delete.delete",
                    "axum::delete_user_delete",
                    "api.users.delete"
                ),
                triple(
                    "users.create_user.post",
                    "axum::create_user",
                    "api.users.create"
                ),
                triple(
                    "users.get_user_get.get",
                    "axum::get_user_get",
                    "api.users.get"
                ),
            ]
        );
    }

    #[test]
    fn test_scan_spec_without_operation_id_does_not_collide() {
        let spec = json!({
            "openapi": "3.1.0",
            "info": {"title": "T", "version": "1.0.0"},
            "paths": {
                "/health": {"get": {"summary": "Health", "responses": {"200": {"description": "OK"}}}},
                "/metrics": {"get": {"summary": "Metrics", "responses": {"200": {"description": "OK"}}}}
            }
        });
        let modules = OpenAPIScanner::new().scan_spec(&spec, None, None).unwrap();
        assert_eq!(
            naming_of(&modules),
            vec![
                triple("health.get", "GET /health", "health.list"),
                triple("metrics.get", "GET /metrics", "metrics.list"),
            ]
        );
    }

    #[test]
    fn test_scan_spec_empty_operation_id_treated_as_absent() {
        let spec = json!({
            "openapi": "3.1.0",
            "info": {"title": "T", "version": "1.0.0"},
            "paths": {"/health": {"get": {"operationId": "", "responses": {"200": {"description": "OK"}}}}}
        });
        let modules = OpenAPIScanner::new().scan_spec(&spec, None, None).unwrap();
        assert_eq!(modules[0].module_id, "health.get");
        assert_eq!(modules[0].target, "GET /health");
    }

    #[test]
    fn test_scan_spec_with_filter() {
        let scanner = OpenAPIScanner::new();
        let spec = sample_spec();
        let modules = scanner.scan_spec(&spec, Some("users"), None).unwrap();
        assert_eq!(modules.len(), 1);
        assert!(modules[0].module_id.contains("users"));
    }

    #[test]
    fn test_scan_spec_invalid_regex_is_regex_error() {
        let result = OpenAPIScanner::new().scan_spec(&sample_spec(), Some("[unclosed"), None);
        assert!(matches!(result, Err(AxumApcoreError::Regex(_))));
    }

    #[test]
    fn test_strip_method_suffix() {
        assert_eq!(strip_method_suffix("get_user_get", "get"), "get_user");
        assert_eq!(
            strip_method_suffix("create_task_post", "post"),
            "create_task"
        );
        assert_eq!(strip_method_suffix("get_user", "get"), "get_user");
        assert_eq!(strip_method_suffix("get_user_get", "GET"), "get_user");
    }

    #[test]
    fn test_scan_spec_skips_non_method_keys() {
        let spec = json!({
            "openapi": "3.1.0",
            "info": {"title": "T", "version": "1.0.0"},
            "paths": {
                "/things": {
                    "summary": "path-level summary",
                    "parameters": [],
                    "get": {"operationId": "list_things_get", "responses": {"200": {"description": "OK"}}}
                }
            }
        });
        let modules = OpenAPIScanner::new().scan_spec(&spec, None, None).unwrap();
        assert_eq!(modules.len(), 1);
        assert_eq!(modules[0].module_id, "default.list_things.get");
    }

    #[test]
    fn test_scan_spec_no_simplify() {
        let scanner = OpenAPIScanner::with_simplify_ids(false);
        let spec = sample_spec();
        let modules = scanner.scan_spec(&spec, None, None).unwrap();

        let get_mod = modules
            .iter()
            .find(|m| m.module_id.contains("get_user"))
            .unwrap();
        assert_eq!(get_mod.module_id, "users.get_user_get.get");
    }

    #[test]
    fn test_scan_spec_empty() {
        let scanner = OpenAPIScanner::new();
        let spec = json!({"openapi": "3.1.0", "paths": {}});
        let modules = scanner.scan_spec(&spec, None, None).unwrap();
        assert!(modules.is_empty());
    }

    #[test]
    fn test_scan_spec_no_paths_is_empty() {
        let scanner = OpenAPIScanner::new();
        let spec = json!({"openapi": "3.1.0"});
        let modules = scanner.scan_spec(&spec, None, None).unwrap();
        assert!(modules.is_empty());
    }

    #[test]
    fn test_scan_spec_rejects_swagger_2() {
        let spec = json!({"swagger": "2.0", "info": {"title": "T", "version": "1"}, "paths": {}});
        let result = OpenAPIScanner::new().scan_spec(&spec, None, None);
        assert!(matches!(result, Err(AxumApcoreError::Scanner(_))));
    }

    #[test]
    fn test_scan_spec_rejects_document_without_openapi_key() {
        let spec = json!({"paths": {}});
        let result = OpenAPIScanner::new().scan_spec(&spec, None, None);
        assert!(matches!(result, Err(AxumApcoreError::Scanner(_))));
    }

    #[test]
    fn test_scan_spec_deprecated_is_annotated() {
        let spec = json!({
            "openapi": "3.1.0",
            "info": {"title": "T", "version": "1.0.0"},
            "paths": {"/old": {"get": {"operationId": "old_get", "deprecated": true,
                                       "responses": {"200": {"description": "OK"}}}}}
        });
        let modules = OpenAPIScanner::new().scan_spec(&spec, None, None).unwrap();
        let annotations = modules[0].annotations.as_ref().unwrap();
        assert_eq!(annotations.extra.get("deprecated"), Some(&json!(true)));
    }

    #[test]
    fn test_scan_spec_version_from_info() {
        let modules = OpenAPIScanner::new()
            .scan_spec(&naming_spec(), None, None)
            .unwrap();
        assert!(modules.iter().all(|m| m.version == "2.5.0"));
    }

    #[test]
    fn test_scan_spec_description_uses_first_line() {
        // Selected by target, not by an `include` pattern: include/exclude
        // match the emitted ID, whose spelling depends on the toolkit release
        // (see `without_uppercase_id_module`).
        let modules = OpenAPIScanner::new()
            .scan_spec(&naming_spec(), None, None)
            .unwrap();
        let module = modules
            .iter()
            .find(|m| m.target == UPPERCASE_ID_TARGET)
            .unwrap();
        assert_eq!(module.description, "Line one");
        assert_eq!(module.documentation.as_deref(), Some("Line one\nLine two"));
    }

    #[test]
    fn test_metadata_stored() {
        let scanner = OpenAPIScanner::new();
        let spec = sample_spec();
        let modules = scanner.scan_spec(&spec, None, None).unwrap();
        let m = &modules[0];
        assert!(m.metadata.contains_key("http_method"));
        assert!(m.metadata.contains_key("url_path"));
        assert!(m.metadata.contains_key("openapi"));
    }

    #[tokio::test]
    async fn test_scan_with_bound_spec() {
        let scanner = OpenAPIScanner::with_spec(sample_spec());
        assert!(scanner.spec().is_some());
        let modules = scanner
            .scan(&axum::Router::new(), Some("tasks"), None)
            .await
            .unwrap();
        assert_eq!(modules.len(), 1);
        assert_eq!(modules[0].module_id, "tasks.create_task.post");
    }

    #[tokio::test]
    async fn test_scan_without_bound_spec_errors() {
        let scanner = OpenAPIScanner::new();
        assert!(scanner.spec().is_none());
        let result = scanner.scan(&axum::Router::new(), None, None).await;
        match result {
            Err(AxumApcoreError::Scanner(msg)) => assert!(msg.contains("with_spec")),
            other => panic!("expected a Scanner error, got {other:?}"),
        }
    }

    /// `scan_spec` is sync; calling it on a single-threaded runtime's only
    /// worker thread must not stall.
    #[tokio::test(flavor = "current_thread")]
    async fn test_scan_spec_inside_current_thread_runtime() {
        let modules = OpenAPIScanner::new()
            .scan_spec(&sample_spec(), None, None)
            .unwrap();
        assert_eq!(modules.len(), 2);
    }

    #[test]
    fn test_resolve_ready_returns_ready_output() {
        assert_eq!(resolve_ready(async { 7 }).unwrap(), 7);
    }

    #[test]
    fn test_resolve_ready_rejects_suspending_future() {
        let result = resolve_ready(futures::future::pending::<()>());
        assert!(matches!(result, Err(AxumApcoreError::Scanner(_))));
    }

    #[test]
    fn test_load_spec_file_json() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("spec.json");
        std::fs::write(&path, sample_spec().to_string()).unwrap();
        let spec = load_spec_file(&path).unwrap();
        assert_eq!(spec, sample_spec());
    }

    #[test]
    fn test_load_spec_file_yaml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("spec.yaml");
        let yaml = "openapi: 3.1.0\n\
                    info: {title: T, version: 1.0.0}\n\
                    paths:\n  \
                      /health:\n    \
                        get:\n      \
                          operationId: health_get\n      \
                          responses:\n        \
                            200:\n          \
                              description: OK\n";
        std::fs::write(&path, yaml).unwrap();
        let spec = load_spec_file(&path).unwrap();
        assert_eq!(spec["openapi"], "3.1.0");
        assert!(spec["paths"]["/health"]["get"]["responses"]["200"].is_object());
        let modules = OpenAPIScanner::new().scan_spec(&spec, None, None).unwrap();
        assert_eq!(modules[0].module_id, "default.health.get");
    }

    #[test]
    fn test_load_spec_file_missing_is_config_error() {
        let result = load_spec_file(Path::new("/nonexistent/axum-apcore/spec.json"));
        match result {
            Err(AxumApcoreError::Config(msg)) => assert!(msg.contains("spec.json")),
            other => panic!("expected a Config error, got {other:?}"),
        }
    }

    #[test]
    fn test_load_spec_file_malformed_is_config_error() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("bad.json");
        std::fs::write(&path, "{not json").unwrap();
        assert!(matches!(
            load_spec_file(&path),
            Err(AxumApcoreError::Config(_))
        ));
    }
}
